on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
name: generate with hugo and push

jobs:

  build:
    name: generate with hugo and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: ./
        env:
          USER_SITE_REPOSITORY: alphaomegadigital/megha-github
          GITHUB_TOKEN: ${{ secrets.JEKYLL_PAT }}
